name: stock-market
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - pystan
  - numpy
  - pandas
  - pip
  - pip:
      - fbprophet==0.7.1
      - streamlit==1.21.0
      - streamlit-tags==1.2.8
      - --find-links https://download.pytorch.org/whl/torch_stable.html
      - neuralprophet==0.5.3
      - yfinance
