name: stock-market
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - numpy
  - pandas
  - pip
  - pip:
      - prophet
      - streamlit
      - streamlit-tags
      - --find-links https://download.pytorch.org/whl/torch_stable.html
      - neuralprophet==0.5.3
      - yfinance
